name: ngrok-ssh
description: SSH into your GitHub Actions runner with ngrok.
inputs:
  NGROK_AUTHTOKEN:
    description: "Your ngrok auth token, required for TCP tunnels."
    required: true
  NGROK_CONFIG_FILE:
    description: "Path to your custom ngrok config file, which will be merged with the default ngrok-ssh config file. See https://ngrok.com/docs/agent/config/#config-file-merging for more information."
    required: false
  SET_RANDOM_PASSWORD:
    description: "Whether to set a random password for the SSH user. If no public key for the SSH user is available, it will be set regardless."
    required: false
    default: false
  SSH_PORT:
    description: "SSH port to use with ngrok."
    required: false
    default: 2222
  SSH_PUBLIC_KEY:
    description: "SSH public key to add to the authorized_keys file."
    required: false
  USE_GITHUB_ACTOR_KEY:
    description: "Whether to add the GITHUB_ACTOR's public keys to the authorized_keys file."
    required: false
    default: true
  WAIT_FOR_CONNECTION:
    description: "Whether to wait for an SSH connection before allowing the workflow run to proceed."
    required: false
    default: false

runs:
  using: "node20"
  main: "main.mjs"
  post: "post.mjs"
