name: ngrok-ssh
description: SSH into your GitHub Actions runner with ngrok.
inputs:
  NGROK_AUTHTOKEN:
    description: "ngrok auth token, required for TCP tunnels"
    required: true
  RANDOM_PASSWORD:
    description: "Set a random password for the SSH user"
    required: false
    default: false
  SSH_PORT:
    description: "SSH port to use with ngrok"
    required: false
    default: 2222
  SSH_PUBLIC_KEY:
    description: "SSH public key to add to the authorized_keys file, in addition to the GITHUB_ACTOR public key"
    required: false

runs:
  using: "node20"
  main: "main.js"
  post: "post.js"
