name: ngrok-ssh
description: SSH into your GitHub Actions runner with ngrok.
inputs:
  BASH_PROFILE:
    description: "Path to a text file to append to the host's .bash_profile."
    required: false
  NGROK_AUTHTOKEN:
    description: "Your ngrok auth token, required for TCP tunnels."
    required: true
  NGROK_CONFIG_FILE:
    description: "Path to your custom ngrok config file, which will be merged with the default ngrok-ssh config file. See https://ngrok.com/docs/agent/config/#config-file-merging for more information."
    required: false
  SET_RANDOM_PASSWORD:
    description: "Whether to set a random password for the SSH user. If no public key for the SSH user is available, it will be set regardless."
    required: false
    default: false
  SSH_PORT:
    description: "SSH port to use with ngrok."
    required: false
    default: 2222
  SSH_CLIENT_PUBLIC_KEY:
    description: "Public key of an SSH client to add to the authorized_keys file."
    required: false
  SSH_HOST_PRIVATE_KEY:
    description: "Private key to use for the SSH host."
    required: false
  SSH_HOST_PUBLIC_KEY:
    description: "Public key to use for the SSH host."
    required: false
  USE_GITHUB_ACTOR_KEY:
    description: "Whether to add the GITHUB_ACTOR's public keys to the authorized_keys file."
    required: false
    default: true
  WAIT_FOR_CONNECTION:
    description: "Whether to wait for an SSH connection before allowing the workflow run to proceed."
    required: false
    default: false
outputs:
  NGROK_TUNNELS:
    description: "JSON representation of provisioned ngrok tunnels from the /api/tunnels endpoint, including any additional configured tunnels."
  SSH_HOSTNAME:
    description: "The hostname of the SSH server."
  SSH_HOST_PUBLIC_KEY:
    description: "The public key of the SSH host."
  SSH_PASSWORD:
    description: "The password of the SSH user, if any."
  SSH_PORT:
    description: "The public port of the SSH server."
  SSH_USER:
    description: "The username of the SSH user."

runs:
  using: "node20"
  main: "src/main.js"
  post: "src/post.js"

branding:
  icon: "terminal"
  color: "green"
