name: Build and save dist file

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "dist/**"

jobs:
  build:
    name: Build and save dist file
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Package
        run: |
          npm ci
          npm run build
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: dist
          push: true
