name: test server
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    container: node:21-slim
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: ngrok-ssh
        with:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
          NGROK_CONFIG_FILE: "test/ngrok.yml"
          SSH_CLIENT_PUBLIC_KEY: ${{ vars.SSH_PUBLIC_KEY }}
      - name: Start SSH client workflow
        run: ./test/run-ssh-client-workflow.js
        env:
          NGROK_TUNNELS: ${{ steps.ngrok-ssh.outputs.NGROK_TUNNELS }}
          SSH_HOSTNAME: ${{ steps.ngrok-ssh.outputs.SSH_HOSTNAME }}
          SSH_USER: ${{ steps.ngrok-ssh.outputs.SSH_USER }}
          SSH_PORT: ${{ steps.ngrok-ssh.outputs.SSH_PORT }}
          SSH_HOST_PUBLIC_KEY: ${{ steps.ngrok-ssh.outputs.SSH_HOST_PUBLIC_KEY }}
          REF: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
      - run: echo "<h1>hello world</h1>" > index.html && npx -y serve
